"""empty message

Revision ID: 800339cb98ab
Revises: 376baf5bc1ea
Create Date: 2021-11-04 11:29:37.592493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800339cb98ab'
down_revision = '376baf5bc1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'category_id')
    op.drop_column('articles', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('author_id', sa.INTEGER(), nullable=False))
    op.add_column('articles', sa.Column('category_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'articles', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(None, 'articles', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
